export const products = [
  {
    id: 0,
    category: 'Cactus',
    family: 'Mamilaria',
    name: 'Blossfeldia',
    potsize: '21',
    precio: '2.500',
    img: 'images/blossfeldia.jpg',
  },
  {
    id: 1,
    category: 'Cactus',
    family: 'Mamilaria',
    name: 'Grusonii',
    potsize: '24',
    precio: '4.200',
    img: 'images/grusonii.jpg',
  },
  {
    id: 2,
    category: 'Cactus',
    family: 'Cereus',
    name: 'San Pedro',
    potsize: '18',
    precio: '3.200',
    img: 'images/sanpedro.jpg',
  },
  {
    id: 3,
    category: 'Suculenta',
    family: 'Echeveria',
    name: 'Perlé',
    potsize: '14',
    precio: '1.200',
    img: 'images/perle.jpg',
  },
  {
    id: 4,
    category: 'Suculenta',
    family: 'Echeveria',
    name: 'Alienor',
    potsize: '15',
    precio: '1.100',
    img: 'images/alienor.jpg',
  },
]
